### ISSUE TITLE
Incompatible with .net 5.0

### ISSUE THREAD

**Issue by neobenedict** [shamork/Toycloud.AspNetCore.Mvc.ModelBinding.BodyAndFormBinding#3]
``` 
           services.AddMvc(o =>
            {
                o.ModelBinderProviders.InsertBodyOrDefaultBinding();
            });
```

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no matching element
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Toycloud.AspNetCore.Mvc.ModelBinding.BodyOrDefaultModelBinderProviderSetup.InsertBodyOrDefaultBinding(IList`1 providers)
   at RayshiftWeb.Startup.<>c__DisplayClass4_0.<ConfigureServices>b__6(MvcOptions o) in C:\Projects\Rayshift\RayshiftWeb\Startup.cs:line 116
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
```

**Comment by shamork** [comment]
I've add support for net5/net6, have a look at the new version and give a try.
I'm closing the issue.
If you still have problem, you can reopen it again.
